@echo off
echo Starting kigruapp Backend...
echo.

echo [1/2] Starting MongoDB + Keycloak (Docker)...
docker-compose up -d mongodb keycloak
echo Waiting for services to initialize...
timeout /t 5 /nobreak >nul

echo [2/2] Starting Backend (Quarkus dev mode on :8200)...
cd /d %~dp0backend
mvnw quarkus:dev
