export const MATERIAL_ICONS: readonly string[] = [
  'access_alarm', 'account_circle', 'add', 'add_circle', 'agriculture',
  'archive', 'arrow_back', 'arrow_forward', 'article', 'assignment',
  'baby_changing_station', 'backpack', 'bakery_dining', 'breakfast_dining',
  'brunch_dining', 'cake', 'calendar_today', 'cancel', 'check', 'check_circle',
  'child_care', 'child_friendly', 'close', 'coffee', 'cookie',
  'dashboard', 'delete', 'dinner_dining', 'edit', 'egg',
  'emoji_food_beverage', 'emoji_people', 'error', 'event', 'face',
  'family_restroom', 'fastfood', 'favorite', 'filter_list', 'flag',
  'food_bank', 'group', 'help', 'home', 'icecream',
  'image', 'image_search', 'info', 'kitchen', 'label',
  'list', 'local_bar', 'local_cafe', 'local_dining', 'local_pizza',
  'lunch_dining', 'manage_accounts', 'menu', 'menu_book', 'more_vert',
  'notifications', 'outdoor_grill', 'people', 'person', 'person_add',
  'phone', 'pie_chart', 'place', 'public', 'ramen_dining',
  'receipt', 'refresh', 'restaurant', 'restaurant_menu', 'rice_bowl',
  'save', 'schedule', 'school', 'search', 'security',
  'send', 'set_meal', 'settings', 'share', 'shopping_cart',
  'spa', 'sports', 'star', 'store', 'table_restaurant',
  'takeout_dining', 'task', 'thumb_up', 'timer', 'today',
  'translate', 'tune', 'verified', 'visibility', 'volunteer_activism',
  'warning', 'water', 'wb_sunny', 'work',
];
